### ISSUE TITLE
TASK: Please help me build python-sphinx 4.1.2 in ELN (nothing provides libpoppler.so.106()(64bit) needed by texlive-pdftex-9:20210325-40.eln112.s390x)

### ISSUE THREAD

**Issue by hroncok** [fedora-eln/eln#65]
### What does the ELN SIG need to do?

The python-sphinx package is outdated in ELN. The current version does not work with Python 3.10.0rc1+ and might block many Python packages from building. I'd like to build python-sphinx-4.1.2-1.eln112 in ELN to unblock the Python packages.

However, I get:

```
DEBUG util.py:444:  Error: 
DEBUG util.py:444:   Problem 1: package texlive-collection-fontsrecommended-9:svn54074-43.eln112.noarch requires texlive-collection-basic, but none of the providers can be installed
DEBUG util.py:444:    - package texlive-collection-basic-9:svn59159-43.eln112.noarch requires texlive-pdftex, but none of the providers can be installed
DEBUG util.py:444:    - conflicting requests
DEBUG util.py:444:    - nothing provides libpoppler.so.106()(64bit) needed by texlive-pdftex-9:20210325-40.eln112.s390x
DEBUG util.py:444:   Problem 2: package texlive-collection-latex-9:svn57048-43.eln112.noarch requires texlive-collection-basic, but none of the providers can be installed
DEBUG util.py:444:    - package texlive-collection-basic-9:svn59159-43.eln112.noarch requires texlive-pdftex, but none of the providers can be installed
DEBUG util.py:444:    - conflicting requests
DEBUG util.py:444:    - nothing provides libpoppler.so.106()(64bit) needed by texlive-pdftex-9:20210325-40.eln112.s390x
```

https://koji.fedoraproject.org/koji/taskinfo?taskID=73772387

Could you please fix this? I'd report a Bugzilla, but there is no ELN product in there and I don't want to bother the Fedora maintainers.

**Comment by sgallagher** [comment]
I'll see what I can do.

**Comment by sgallagher** [comment]
Looks like another unannounced poppler soname bump in Rawhide. I'll rebuild the dependent packages in ELN

**Comment by sgallagher** [comment]
I'm rebuilding [texlive](https://koji.fedoraproject.org/koji/taskinfo?taskID=73959636) at the moment, which is a dependency for this.

**Comment by sgallagher** [comment]
Sphinx has been built successfully.
